// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyirdgwjevudetqjeyft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5aXJkZ3dqZXZ1ZGV0cWpleWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODM3NDIsImV4cCI6MjA2NTA1OTc0Mn0.QbBBNffxSyRwLcQv1juORgLYiCdWwhH7wpD2N76S-Gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);